# -*- coding: utf-8 -*-
"""MeanZtier_MerchantID_last12M

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyNMtJPy-48rmJFdfs01UFXf1c9uxrEX
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['Z_Score_Merchant_Monthly.csv']))

df

#Convert to date64type
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

df.info()

#Sort ID&Date
df2 = df.set_index(['MerchantID','Date'])

#Keep last 12M
df2 = df.groupby('MerchantID').tail(12)

#Download CSV
df2.to_csv('df2.csv')
from google.colab import files
files.download("df2.csv")

#Mean groupby ID
aggregate = df.groupby('MerchantID').mean()

aggregate

newdf = df2.agg(['sum', 'max','mean'])

newdf